EZP-31462: Add handling unsupported password hash type by redirection to a password reset
ezsystems/ezplatform-user pull request #75
Opened 2020-08-25 07:28 UTC by kaff

| Question      | Answer
| ------------- | ---
| Tickets       |  [EZP-31462](https://jira.ez.no/browse/EZP-31462)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | ?
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

In order to handle users with unsupported hash types redirection to "Password reset" was added

#### Checklist:
- [ ] Implement tests
- [ ] Coding standards (`$ composer fix-cs`)

2020-08-28 06:28 UTC, ViniTou requested changes

2020-08-28 06:28 UTC, ViniTou commented on src/bundle/Controller/PasswordResetController.php
> +    public function userForgotPasswordAction(Request $request, string $reason = null)
```suggestion
    public function userForgotPasswordAction(Request $request, ?string $reason = null)
```

2020-08-28 06:28 UTC, ViniTou commented on src/bundle/Type/UserForgotPasswordReason.php
> +    const MIGRATION = 'migration';
```suggestion
    public const MIGRATION = 'migration';
```

2020-08-28 06:28 UTC, ViniTou commented on tests/Behat/Context/UserSetupContext.php
> +    /** @var Connection */
```suggestion
    /** @var \Doctrine\DBAL\Connection */
```

2020-08-28 06:28 UTC, ViniTou commented on tests/Behat/Context/UserSetupContext.php
> +    public function aUserHasPasswordInUnsupportedFormat($login)
```suggestion
    public function aUserHasPasswordInUnsupportedFormat(string $login): void
```

2020-08-28 06:28 UTC, ViniTou commented on .travis.yml
> +  - if [ "${CHECK_CS}" == "1" -o "${PHPUNIT_CONFIG}" != "" ]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest ; fi
I think beacuse you use `PHPUNIT_CONFIG` and `TEST_CONFIG` for running test (line 48) unit tests are failing on travis.

2020-08-28 07:11 UTC, mnocon requested changes
Small changes to Travis setup are needed - Behat part looks good! 😎

2020-08-28 07:11 UTC, mnocon commented on .travis.yml
> +  - if [ "${SETUP_BEHAT_OPTS}" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "bin/ezbehat $SETUP_BEHAT_OPTS" ; fi
This part should be removed (we're not using SETUP_BEHAT_OPTS).

The `script` section should look like this:
```
script:
- if [ "$TEST_CONFIG" != "" ] ; then php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1
  vendor/bin/phpunit -c $TEST_CONFIG ; fi
- if [ "$CHECK_CS" == "1" ] ; then ./vendor/bin/php-cs-fixer fix -v --dry-run --show-progress=estimating; fi
- if [ "${BEHAT_OPTS}" != "" ]; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "bin/ezbehat ${BEHAT_OPTS}" ; fi
```

2020-08-28 07:11 UTC, mnocon commented on composer.json
> +        "_ezplatform_branch_for_behat_tests": "master",
```suggestion
        "_ezplatform_branch_for_behat_tests": "3.1",
```
We should use `master` for `master` branch, ezplatform-user 2.1 is used in Platform 3.1

2020-08-28 07:11 UTC, mnocon commented on .travis.yml
> +  - name: "Workflow Integration tests"
```suggestion
  - name: "User Integration tests"
```
Or something similar 😉

2020-08-28 11:03 UTC, kaff commented on .travis.yml
> +  - if [ "${CHECK_CS}" == "1" -o "${PHPUNIT_CONFIG}" != "" ]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest ; fi
fixed

2020-08-28 11:22 UTC, Nattfarinn approved these changes

2020-08-28 11:22 UTC, Nattfarinn commented on behat_suites.yml
> +              - '%paths.base%/vendor/ezsystems/ezplatform-user/features/browser'
Keep indent consistent within the file (4 spaces)

2020-08-28 11:22 UTC, Nattfarinn commented on src/bundle/Resources/views/forgot_password/index.html.twig
> +    {% if reason is defined and reason == constant('\\EzSystems\\EzPlatformUserBundle\\Type\\UserForgotPasswordReason::MIGRATION') %}
Would be cleaner to inject constant value as parameter

2020-08-31 05:43 UTC, kaff commented on behat_suites.yml
> +              - '%paths.base%/vendor/ezsystems/ezplatform-user/features/browser'
fixed

2020-08-31 07:37 UTC, ViniTou approved these changes

2020-08-31 07:46 UTC, mnocon reviewed
+1 for Travis/Behat

2020-09-11 13:54 UTC, micszo requested changes
As agreed in the call writing down found issues:

1. The exception `Argument 'hashType' is invalid: Password hash type '2' is not recognized` is now handled correctly when user attempts to log in (redirect happens) but it also occurs in the next step when user tries to change his password on the reset password page. The page just reloads without any message (which is a general issue, see e.g. https://jira.ez.no/browse/EZP-31854, https://jira.ez.no/browse/EZP-31304) but when user later logs in (with correct hash type) into admin panel the exception can be seen.
2. There are two paths in this case. User can try to log in on frontend or into admin. Both templates need to be updated with the new message about the password having expired. Namely: `/admin/user/reset-password/` and `/user/reset-password/`.

2020-09-22 07:09 UTC, mikadamczyk approved these changes

2020-09-28 12:26 UTC, micszo approved these changes
Retested successfully, the above issues do not occur anymore.
QA Approved on eZ Platform EE v3.1.2 with branches.

2020-09-28 12:37 UTC, merged