EZP-31825: Use "updateUserPassword" is newer ezplatform-kernel is available
ezsystems/ezplatform-user pull request #80
Opened 2020-10-15 06:30 UTC by Steveb-p

| Question      | Answer
| ------------- | ---
| Tickets       |  [EZP-31825](https://jira.ez.no/browse/EZP-31825)
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes/no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Related to https://github.com/ezsystems/ezplatform-kernel/pull/117

#### Checklist:
- [ ] Implement tests
- [ ] Coding standards (`$ composer fix-cs`)

2020-10-15 07:17 UTC, ViniTou commented on src/bundle/Controller/PasswordChangeController.php
> +                if (method_exists($this->userService, 'updateUserPassword')) {
There is no point of doing it that way, both versions (this and kernel) gonna released at the same time. What you should do is rebase this PR against 1.0 branch.

2020-10-15 07:43 UTC, alongosz requested changes

2020-10-15 07:43 UTC, alongosz commented on src/bundle/Controller/PasswordChangeController.php
> +                if (method_exists($this->userService, 'updateUserPassword')) {
> There is no point of doing it that way, both versions (this and kernel) gonna released at the same time. What you should do is rebase this PR against 2.1 branch.

@Steveb-p :point_up: bump required ezplatform-kernel version instead

2020-10-20 12:24 UTC, Steveb-p commented on src/bundle/Controller/PasswordChangeController.php
> +                if (method_exists($this->userService, 'updateUserPassword')) {
@alongosz @ViniTou what version should be targetted?

2020-10-20 16:02 UTC, alongosz commented on src/bundle/Controller/PasswordChangeController.php
> +                if (method_exists($this->userService, 'updateUserPassword')) {
@Steveb-p https://github.com/ezsystems/ezplatform-user/blob/master/composer.json#L21 actually it's already ok - ^1.2@dev, didn't notice

2020-10-20 17:03 UTC, alongosz approved these changes

2020-10-21 07:25 UTC, ViniTou approved these changes

2020-10-22 11:44 UTC, tomaszszopinski approved these changes
QA approved on eZPlatform-ee 3.1.2 with diff & path.

2020-10-22 11:46 UTC, merged